### ISSUE TITLE
Problème d'enregistrement d'un flux

### ISSUE THREAD

**Issue by slobberbone** [NextDom/plugin-RTSP#17]
## Description
Lorsque l'on enregistre un flux, l'erreur suivante est levée : Le champs Résolution doit être au format nombrexnombre (ex 1280x720)

## Etapes à reproduire (pour les bugs)

1.Renseigner un nouvel équipement ou modifier un existant
2.Enregistrer

## Environnement:

* **Version Jeedom**:3.2.3
* **Plateforme**:Raspberry Pi 3
* **Version du Plugin**: 10a10dfdf3792a799e2a44fde1118eab88a71b4b

**Comment by slobberbone** [comment]
Bug suite à une factorisation de code concernant le contrôle de la résolution. Ca n'a plus lieu d'être car c'est une liste fermée dorénavant.

**Comment by slobberbone** [comment]
Mauvais factoring : 
`private function pregMatchPaternConfiguration()
    {
        return "#[0-9][0-9][0-9][0-9]x[0-9][0-9][0-9][0-9]$#";
    }
`

Devait controler qu'une serie de chiffre, pas 4x4 ... d'où le bug.

**Comment by slobberbone** [comment]
Corrigé : 85d1043fbd2d4bb3ed7444728aa896200d325415

**Comment by ColonelMoutarde** [comment]
C’est pour tant le même pattern à chaque fois

**Comment by aztazt** [comment]
Le bon pattern eût été : #[0-9]{1-4}x[0-9]{1-4}$#
