### ISSUE TITLE
Icon flux rtsp

### ISSUE THREAD

**Issue by Guitool2010** [NextDom/plugin-RTSP#19]
## Description

Affichage de l'icone dans la gestion de mes flux rtsp 
![capture](https://user-images.githubusercontent.com/39554687/40498995-2354d850-5f70-11e8-8c98-f2d11bdee786.PNG)

## Environnement:

* **Version Jeedom**: 3.2.7
* **Plateforme**: Debian
* **Version du Plugin**: 2.2.5

**Comment by Guitool2010** [comment]
des nouvelles de ce bug ??

**Comment by nextdom-user** [comment]
Non dsl je n'ai pas vraiment regardé depuis mais dès que j'ai une caméra je te redis ça !
