### ISSUE TITLE
Le champs Resolution doit être au format nombrexnombre.

### ISSUE THREAD

**Issue by YinZhEFr** [NextDom/plugin-RTSP#21]
## Description
Lors de la sauvegarde d'une configuration de flux, le message d'erreur suivant survient et ne permet pas l'enregistrement de la configuration : "Le champ resolution doit être au format nombrexnombre (ex:1280x720)"

## Etapes à reproduire (pour les bugs)

1. Configurer un flux video
2. sauvegarder
3.
4.

## Contexte:
Lors de l'ajout d'un flux video.

## Environnement:

* **Version Jeedom**: 3.2.7
* **Plateforme**: Raspberry pi3 B+
* **Version du Plugin**: 5abc2c3daf4d97a95adcf33a6335cd93841e3230

**Comment by slobberbone** [comment]
Salut, c'est corrigé ici : e48be4c740e1a975eb62e6f615e289bc80b8401a
Si tu installes le plugin : https://github.com/NextDom/plugin-AlternativeMarketForJeedom il va te notifier des maj ;)

**Comment by YinZhEFr** [comment]
OK. Super.
Quand on est pas Developpeur… c’est un peu la lutte de s’y retrouver :)
Merci de la réponse rapide.

Alex

**Comment by slobberbone** [comment]
Pas de soucis, c'est pour ça que la commuanuté à développé le plugin AlternativeMarketForJeedom qui permet d'installer n'importe quel plugin Jeedom/NextDom sans passer par un serveur tiers Jeedom qui limite les dépots de plugins.
