### ISSUE TITLE
Installation dépendances sous debian 10 (buster)

### ISSUE THREAD

**Issue by TekiStone** [NextDom/plugin-RTSP#26]
## Description

L'installation des dépendances ne fonctionne pas sous Debian 10 dû à la suppression du packet libav-tools.

## Etapes à reproduire (pour les bugs)

1.Installer le plugin depuis le Nextdom Market
2.Aller voir dans les logs "RTSP_dep"
3.Voir le message suivant
![image](https://user-images.githubusercontent.com/35001669/72259465-d5a5a200-3610-11ea-94bf-a5157e96b543.png)
4.Les dépendances ne sont pas installées 

## Environnement:

* **Version Jeedom**: 0.6.1
* **Plateforme**:rPi
* **Version du Plugin**:6059cf75ff683316764bf36e104a0d6d9431b533

**Comment by Gis70** [comment]
Salut, du coup ça ne fonctionne plus ? essaye d'installer la lib là : libavcodec58

**Comment by TekiStone** [comment]
Hello,
C'est surtout qu'il essaye de les installer toutes les x minutes.
Je ne sais pas si le plugin ne fonctionne pas à cause de ça, j'obtiens ça 
![image](https://user-images.githubusercontent.com/35001669/72270176-0abbef80-3625-11ea-9698-665c73aec885.png)
Avec les mêmes paramètres sous VLC j'obtiens bien l'image

La lib libavcodec58 était déjà installé sur la machine

**Comment by Arkezis** [comment]
Pareil ici, depuis la dernière mise à jour `6059cf75ff683316764bf36e104a0d6d9431b533` , le plugin ne remonte plus d'image (pas de soucis sur VLC), alors que ça marchait sans soucis avant.
J'ai aussi l'install de `libav-tools` qui se fait pas pendant les deps

**Comment by slobberbone** [comment]
Tiens te revoilà la @Arkezis ;-) le monde est petit ! Viens nous voir sur le discord nextdom ;-) 
Alors pour la version buster, le paquet à tout simplement disparu... D'où le soucis. 
Avconv était un fork de ffmpeg donc à priori il faut basculer sur ce paquet. Seul soucis la commande n'est pas en un pour un et j'avais utilisé avconv car avec ffmpeg je j'arrivai pas à faire la même chose. 
De plus je n'ai plus de caméra, donc compliqué de tester... 
Si l'un de vous à l'équivalent de la commande avconv du plugin en ffmpeg,  je peux l'intégrer.

**Comment by shinkhell** [comment]
Bonjour! Si jamais quelqu'un se pose la question de comment régler les dépendances, il faut se rendre sur libav.org et build la dépendance soi-même :
cd ~/
wget https://libav.org/releases/libav-12.3.tar.xz
tar xf libav-12.3.tar.xz
cd libav-12.3
./configure (ou sudo si besoin)
./make
sudo make install
cd /usr/bin
sudo ln -s ../local/bin/avconv avconv

Puis relancer les dépendances : il semble que ça fasse l'affaire.
En espérant avoir aidé!

**Comment by ColonelMoutarde** [comment]
Merci Baptiste pour ton aide. Je suis content d’avoir de tes nouvelles. 😀

**Comment by slobberbone** [comment]
Super merci, je maj le plugin demain @shinkhell !

**Comment by slobberbone** [comment]
Fix en cours : https://github.com/NextDom/plugin-RTSP/tree/ffmpegConvert

**Comment by slobberbone** [comment]
Fixed in https://github.com/NextDom/plugin-RTSP/pull/29
