### ISSUE TITLE
Docs au nouveau standard de la team (github pages)

### ISSUE THREAD

**Issue by byackee** [NextDom/plugin-RTSP#3]
Utilisation de Github pages, template disponible dans le repo plugin-template de la team

Aller voir le wiki: https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/Documentation-d'un-Plugin

**Comment by slobberbone** [comment]
Fait : 0e7e91f3621dc8628f1d7db5191b49829c3d0890
